name: TaskNavigationApp
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^0.13.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo_moderna.png
