name: TaskNavigationApp
description: A new Flutter project.

# Versões de ambiente (exemplo)
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:

    - assets/logo_moderna.png







# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
